### ISSUE TITLE
Polling blocks from nodes

### ISSUE THREAD

**Issue by jollen** [flowchain/blockchain-starter-kit#1]

**Comment by sanamoin7** [comment]
Hi, in this version in the libs/mining.js file the line of code 122 -  key = '0' + key.slice(0, index); 
Why this key is set to 0? I mean we can change it and notice the change in result but why 0 is chosen to place at the start of the difficulty.

**Comment by jollen** [comment]
Hi @sanamoin7 ,

The leading 0 is chosen to control the mining difficulty. More 0s are put in the leading of the key, more difficult to find a block. Accordingly, the method was presented in the Satoshi Blockchain system (the Bitcoin blockchain). Therefore, the code follows the Satoshi Blockchain's method and put leading 0s to determine the mining difficulty.

Hope my answer will help you.
